const SECONDARY_COLORS = {
    SECONDARY_GREEN: '#8FC351',
    SECONDARY_PURPLE: '#8A74AD',
    SECONDARY_YELLOW: '#FFC307',
    SECONDARY_RED: '#EA645E',
    SECONDARY_GRAY: '#C4C6C8'
}


export default SECONDARY_COLORS
